scoop install main/7zip
scoop install main/curl
scoop install main/diffutils
scoop install main/exiftool
scoop install main/ffmpeg
scoop install main/grep
scoop install main/imagemagick
scoop install main/just
scoop install main/less
scoop install main/megatools
scoop install main/nano
scoop install main/netcat
scoop install main/ngrok
scoop install main/ntop
scoop install main/pwsh
scoop install main/rclone
scoop install main/rhash
scoop install main/time
scoop install main/which
scoop install main/yt-dlp
scoop install sysinternals/contig
